const nowIso = () => new Date().toISOString();

export const REFERENCE_MARKET_ROWS = [
  {
    id: "feed-wheat",
    market: "cereals",
    commodity: "Feed Wheat",
    price: 190,
    unit: "£/t",
    currency: "GBP",
    basis: "UK delivered reference",
    region: "UK",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/cereals-oilseeds/futures-prices",
    trend: "flat",
  },
  {
    id: "milling-wheat",
    market: "cereals",
    commodity: "Milling Wheat",
    price: 228,
    unit: "£/t",
    currency: "GBP",
    basis: "UK delivered reference",
    region: "UK",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/cereals-oilseeds/futures-prices",
    trend: "flat",
  },
  {
    id: "feed-barley",
    market: "cereals",
    commodity: "Feed Barley",
    price: 168,
    unit: "£/t",
    currency: "GBP",
    basis: "UK delivered reference",
    region: "UK",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/cereals-oilseeds/futures-prices",
    trend: "flat",
  },
  {
    id: "malting-barley",
    market: "cereals",
    commodity: "Malting Barley",
    price: 195,
    unit: "£/t",
    currency: "GBP",
    basis: "UK delivered reference",
    region: "UK",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/cereals-oilseeds/futures-prices",
    trend: "flat",
  },
  {
    id: "osr",
    market: "cereals",
    commodity: "Oilseed Rape",
    price: 372,
    unit: "£/t",
    currency: "GBP",
    basis: "UK delivered reference",
    region: "UK",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/cereals-oilseeds/futures-prices",
    trend: "flat",
  },
  {
    id: "beans",
    market: "cereals",
    commodity: "Beans",
    price: 225,
    unit: "£/t",
    currency: "GBP",
    basis: "UK delivered reference",
    region: "UK",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/cereals-oilseeds/feed-ingredient-prices",
    trend: "flat",
  },
  {
    id: "deadweight-cattle",
    market: "livestock",
    commodity: "GB deadweight cattle",
    price: 520,
    unit: "p/kg",
    currency: "GBP",
    basis: "GB deadweight reference",
    region: "GB",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/beef/gb-deadweight-cattle-prices",
    trend: "flat",
  },
  {
    id: "deadweight-lamb",
    market: "livestock",
    commodity: "GB deadweight lamb",
    price: 640,
    unit: "p/kg",
    currency: "GBP",
    basis: "GB deadweight reference",
    region: "GB",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/lamb/gb-deadweight-sheep-prices",
    trend: "flat",
  },
  {
    id: "deadweight-pigs",
    market: "livestock",
    commodity: "GB deadweight pigs",
    price: 215,
    unit: "p/kg",
    currency: "GBP",
    basis: "GB deadweight reference",
    region: "GB",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/pork/gb-deadweight-pig-prices-uk-spec",
    trend: "flat",
  },
  {
    id: "farmgate-milk",
    market: "dairy",
    commodity: "Farmgate milk",
    price: 39,
    unit: "p/litre",
    currency: "GBP",
    basis: "UK farmgate reference",
    region: "UK",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/dairy/uk-producer-numbers",
    trend: "flat",
  },
  {
    id: "input-ammonium-nitrate",
    market: "inputs",
    commodity: "Ammonium Nitrate (34.5%N)",
    price: 330,
    unit: "£/t",
    currency: "GBP",
    basis: "GB fertiliser reference",
    region: "GB",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/GB-fertiliser-prices",
    trend: "flat",
  },
  {
    id: "input-urea",
    market: "inputs",
    commodity: "Urea (46%N)",
    price: 370,
    unit: "£/t",
    currency: "GBP",
    basis: "GB fertiliser reference",
    region: "GB",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/GB-fertiliser-prices",
    trend: "flat",
  },
  {
    id: "input-dap",
    market: "inputs",
    commodity: "DAP (18-46-0)",
    price: 520,
    unit: "£/t",
    currency: "GBP",
    basis: "GB fertiliser reference",
    region: "GB",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/GB-fertiliser-prices",
    trend: "flat",
  },
  {
    id: "input-red-diesel",
    market: "inputs",
    commodity: "Red diesel",
    price: 0.72,
    unit: "£/L",
    currency: "GBP",
    basis: "Farm fuel reference",
    region: "UK",
    source: "AHDB reference",
    sourceUrl: "https://ahdb.org.uk/fuel-prices",
    trend: "flat",
  },
];

export function referenceRows({ stale = true, provider = "reference" } = {}) {
  const updatedAt = nowIso();
  return REFERENCE_MARKET_ROWS.map((row) => ({
    ...row,
    updatedAt,
    confidence: provider === "reference" ? "reference" : "medium",
    stale,
  }));
}
